export default {
  XSmallLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "Light",
    lineHeight: "120%",
    fontSize: "15px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  XSmallThin: {
    fontFamily: "Roboto Slab",
    fontWeight: "Thin",
    lineHeight: "120%",
    fontSize: "15px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  SmallLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "Light",
    lineHeight: "120%",
    fontSize: "19px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  BaseLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "Light",
    lineHeight: "120%",
    fontSize: "24px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  LargeLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "Light",
    lineHeight: "120%",
    fontSize: "30px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  Heading6Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "38px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  Heading5Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "47px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  Heading4Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "59px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  Heading3Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "73px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  Heading2Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "92px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
  Heading1Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "114px",
    letterSpacing: "0%",
    paragraphSpacing: "0",
    paragraphIndent: "0",
    textCase: "none",
    textDecoration: "none",
  },
};
