export default {
  XSmallLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "300",
    lineHeight: "120%",
    fontSize: "15px",
    margin: 0,
  },
  XSmallThin: {
    fontFamily: "Roboto Slab",
    fontWeight: "100",
    lineHeight: "120%",
    fontSize: "15px",
    margin: 0,
  },
  SmallLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "300",
    lineHeight: "120%",
    fontSize: "19px",
    margin: 0,
  },
  BaseLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "300",
    lineHeight: "120%",
    fontSize: "24px",
    margin: 0,
  },
  LargeLight: {
    fontFamily: "Roboto Slab",
    fontWeight: "300",
    lineHeight: "120%",
    fontSize: "30px",
    margin: 0,
  },
  Heading6Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "38px",
    margin: 0,
    padding: 0,
  },
  Heading5Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "47px",
    margin: 0,
    padding: 0,
  },
  Heading4Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "59px",
    margin: 0,
    padding: 0,
  },
  Heading3Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "73px",
    margin: 0,
    padding: 0,
  },
  Heading2Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "92px",
    margin: 0,
    padding: 0,
  },
  Heading1Regular: {
    fontFamily: "Londrina Outline",
    fontWeight: "Normal",
    lineHeight: "120%",
    fontSize: "114px",
    margin: 0,
    padding: 0,
  },
};
